/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algo;

public class App {
  public static void main(String[] args) {
    //    System.out.println(App.getGreeting());
  }

  static String getGreeting() {
    return "Hello World!";
  }
}
